name: build

on: 
  push:
    branches:
      - compile

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: my-project
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: my-project.exe
            command: both

          # - release_for: macOS-x86_64
          #   os: macOS-latest
          #   target: x86_64-apple-darwin
          #   bin: precious
          #   name: precious-Darwin-x86_64.tar.gz
          #   command: both

            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-project-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

    # more packaging stuff goes here ...