name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: find my shit
        run: pwd && ls -lah my-project*
      # - name: Upload Binaries to Release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     file: my-project*/*
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.ref }}
      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "my-project*/my-project*"
          allowUpdates: true
